name: flutter_jr_hackathon
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  build_runner: ^2.4.13
  freezed: ^2.5.7
  riverpod_annotation: ^2.6.1
  flutter_riverpod: ^2.6.1
  firebase_core: ^3.12.1
  uuid: ^4.5.1
  freezed_annotation: ^2.4.4
  cloud_firestore: ^5.6.5
  gap: ^3.0.1
  percent_indicator: ^4.2.4

dev_dependencies:
  json_serializable: ^6.9.0
  riverpod_generator: ^2.6.3
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/