// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPOhHCek-k7DBWvCc5kJRA5lRc5nxarxc',
    appId: '1:943174157711:web:d03e42566e0ee3e0cab7fa',
    messagingSenderId: '943174157711',
    projectId: 'flutterjrhackathon',
    authDomain: 'flutterjrhackathon.firebaseapp.com',
    storageBucket: 'flutterjrhackathon.firebasestorage.app',
    measurementId: 'G-FVJF3GHTYW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC18DxSXI56ELtQ5-3e5s7bfj1fnKWUD_o',
    appId: '1:943174157711:android:9854fbfc54012856cab7fa',
    messagingSenderId: '943174157711',
    projectId: 'flutterjrhackathon',
    storageBucket: 'flutterjrhackathon.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGpsyGI_1_2Daw4E_RTVrs4kVdZg3Rjkk',
    appId: '1:943174157711:ios:760f4c4e5d14b3c1cab7fa',
    messagingSenderId: '943174157711',
    projectId: 'flutterjrhackathon',
    storageBucket: 'flutterjrhackathon.firebasestorage.app',
    iosBundleId: 'com.example.flutterJrHackathon',
  );
}
